export const GETPOST = 'GETPOST'
export const GETPOST_SUCCESS = 'GETPOST_SUCCESS'
export const GETPOST_FAIL = 'GETPOST_FAIL'
export const GETTING_POST = 'GETTING_POST'
//
export const ADDPOST = 'ADDPOST'
export const ADDPOST_SUCCESS = 'ADDPOSTSUCCESS'
export const ADDPOST_FAIL = 'ADDPOST_FAIL'
export const ADDING_POST = 'ADDING_POST'
//
export const LIKE = 'LIKE'
//
export const ADD_COMMENT = 'ADD_COMMENT'
export const ADDING_COMMENT = 'ADDING_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL'
